version: '3'
services:
  backend-api:
    container_name: docker-backend
    build: .
    ports:
      - '8000:8000'
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    restart: always
    volumes:
      - .:/app
      - nodemodules:/src/node_modules
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'    
    volumes:
      - mongo_db_container:/data/db
    restart: always
  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
volumes:
  nodemodules:
  mongo_db_container: 