### Authentication
### regitration
POST http://localhost:8000/api/auth/register
Content-Type: application/json

{   
    "username": "stonecode",
    "email" : "stonecode@local.dev",
    "password": "stonecode"
}
### Login
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{ 
    "email": "stonecode@local.dev",
    "password": "stonecode"
}
### logout
Get http://localhost:8000/api/auth/logout
### refresh token
Get http://localhost:8000/api/auth/refresh_token
### User
// Get All
Get http://localhost:8000/api/users/all/

### 
Get http://localhost:8000/api/users/user/634ab196c33e97fe3790331f

### MEDIAS

Get http://localhost:8000/api/medias/all/

### create new media (image or video)
POST  http://localhost:8000/api/medias/new_media
Content-Type: application/json

{
    "path" : "mysupervideo.mkv", 
    "type" : "video"

}

### MEDIAS

Get http://localhost:8000/api/posts/all/

### create new media (image or video)
POST  http://localhost:8000/api/posts/new_post
Content-Type: application/json

{
    "title" : "post", 
    "description" : "my second article on internet",
    "author": "633d870388422ca4a99a43c1",
    "medias": ["633d8a766e059a3213b31247","633d8a996e059a3213b3124d"]

}

###
Get http://localhost:8000/api/posts/post/633d90817cb8511ba1a5ecdb


